import { Tender } from '@/types/tender';
import { Bidder } from '@/types/bidder';

export interface SampleTenderData {
  tender: Tender;
  bidders: Bidder[];
}

export const SAMPLE_TENDERS: SampleTenderData[] = [
  // =========================================================================
  // TENDER 1: IT Equipment & Laptops (Cartel / Debarred / MSME / High Gaps)
  // =========================================================================
  {
    tender: {
      id: 'TND-2026-IT-89421',
      tenderNumber: 'GeM/2026/B/89421',
      title: 'Supply, Installation & Maintenance of Enterprise Laptops and Workstations',
      category: 'GOODS',
      estimatedValue: 48000000, // ₹4.80 Cr
      publishedDate: '2026-08-01',
      closingDate: '2026-08-30',
      authority: {
        name: 'National Informatics Centre (NIC)',
        department: 'Ministry of Electronics & Information Technology (MeitY)',
        location: 'CGO Complex, Lodhi Road, New Delhi - 110003',
      },
      description: 'Procurement of 600 Core-i7 14th Gen Enterprise Laptops with 3-Year On-Site Comprehensive OEM Warranty and Pre-loaded Ubuntu/Windows Gov Image.',
      requiredDocuments: [
        'GST Registration Certificate (Form REG-06)',
        'PAN Card',
        'MCA21 Certificate of Incorporation',
        'OEM Authorization Form (MAF)',
        'Make in India Local Content Declaration',
        'Audited Balance Sheets (Last 3 FYs)',
      ],
      clauses: [
        {
          id: 'CLS_DEBAR_1',
          clauseNumber: 'Clause 4.1(a)',
          title: 'Debarment & Blacklisting Clearance',
          text: 'Bidders debarred by CVC, GeM, or any Central/State Ministry under GFR 2017 Rule 151 are ineligible.',
          type: 'HARD_GATE',
          category: 'DEBARMENT',
          defaultWeight: 0,
          isMandatory: true,
          applicableInCategories: ['GOODS', 'SERVICES', 'WORKS'],
        },
        {
          id: 'CLS_MCA_1',
          clauseNumber: 'Clause 2.1(b)',
          title: 'Active Corporate Legal Entity Status',
          text: 'Incorporated entities must have Active status under Ministry of Corporate Affairs (MCA21).',
          type: 'HARD_GATE',
          category: 'MCA21_STATUS',
          defaultWeight: 0,
          isMandatory: true,
          applicableInCategories: ['GOODS', 'SERVICES', 'WORKS'],
        },
        {
          id: 'CLS_GST_1',
          clauseNumber: 'Clause 3.1',
          title: 'GST Return Filing & Tax Compliance',
          text: 'Bidder must hold active GSTIN with regular GSTR-3B filings for the preceding 6 months.',
          type: 'WEIGHTED_CHECK',
          category: 'GST',
          defaultWeight: 20,
          isMandatory: true,
          applicableInCategories: ['GOODS', 'SERVICES', 'WORKS'],
        },
        {
          id: 'CLS_PAN_1',
          clauseNumber: 'Clause 3.2',
          title: 'PAN & Income Tax Compliance',
          text: 'Valid PAN and filed ITR for the preceding Assessment Year.',
          type: 'WEIGHTED_CHECK',
          category: 'PAN',
          defaultWeight: 15,
          isMandatory: true,
          applicableInCategories: ['GOODS', 'SERVICES', 'WORKS'],
        },
        {
          id: 'CLS_UDYAM_1',
          clauseNumber: 'Clause 5.1',
          title: 'MSME Policy Preference & EMD Exemption',
          text: 'Udyam registered MSEs are entitled to EMD exemption and 25% purchase preference.',
          type: 'WEIGHTED_CHECK',
          category: 'UDYAM',
          defaultWeight: 15,
          isMandatory: false,
          applicableInCategories: ['GOODS', 'SERVICES', 'WORKS'],
          exemptionForMSME: true,
        },
        {
          id: 'CLS_MII_1',
          clauseNumber: 'Clause 8.1',
          title: 'Make in India Local Content Preference',
          text: 'Class-I Local Supplier (≥50% local content) and Class-II (≥20%) preference as per DPIIT PPO-2017.',
          type: 'WEIGHTED_CHECK',
          category: 'MAKE_IN_INDIA',
          defaultWeight: 15,
          isMandatory: true,
          applicableInCategories: ['GOODS', 'WORKS'],
        },
        {
          id: 'CLS_OEM_1',
          clauseNumber: 'Clause 9.4',
          title: 'Manufacturer Authorization Form (MAF)',
          text: 'Direct OEM or authorized tier-1 partner with OEM authorization letter required.',
          type: 'WEIGHTED_CHECK',
          category: 'OEM_AUTH',
          defaultWeight: 15,
          isMandatory: true,
          applicableInCategories: ['GOODS'],
        },
        {
          id: 'CLS_FIN_1',
          clauseNumber: 'Clause 2.4',
          title: 'Financial Turnover & AI Claim Reconciliation',
          text: 'Average annual financial turnover of minimum ₹2.00 Cr in last 3 FYs with CA UDIN certification.',
          type: 'WEIGHTED_CHECK',
          category: 'FINANCIAL_TURNOVER',
          defaultWeight: 10,
          isMandatory: true,
          applicableInCategories: ['GOODS', 'SERVICES', 'WORKS'],
        },
      ],
    },
    bidders: [
      // Bidder 1: TechPro SysTech Pvt Ltd (Collusion Ring Member A)
      {
        id: 'BID-001',
        tenderId: 'TND-2026-IT-89421',
        name: 'TechPro SysTech Private Limited',
        tradeName: 'TechPro Systems',
        cin: 'U72200DL2021PTC376120',
        pan: 'AAACT4819M',
        gstin: '07AAACT4819M1Z8',
        udyamNumber: 'UDYAM-DL-08-0019284',
        isMsme: true,
        isStartup: false,
        incorporationDate: '2021-02-10',
        registeredAddress: 'Plot 14, Okhla Industrial Area Phase-III, New Delhi - 110020',
        statutoryAuditor: 'M/s K.R. Sharma & Associates Chartered Accountants',
        directors: [
          {
            din: '08412948',
            name: 'Sunil Kumar Verma',
            pan: 'ABIPV8812K',
            appointmentDate: '2021-02-10',
          },
          {
            din: '07194820',
            name: 'Raman Gupta',
            pan: 'AAAPG9921D',
            appointmentDate: '2021-02-10',
          },
        ],
        mcaFilings: {
          cin: 'U72200DL2021PTC376120',
          companyName: 'TechPro SysTech Private Limited',
          status: 'ACTIVE',
          rocCode: 'RoC-Delhi',
          registrationNumber: '376120',
          category: 'Company limited by Shares',
          lastAgmDate: '2025-09-28',
          balanceSheetDate: '2025-03-31',
          statutoryAuditor: 'M/s K.R. Sharma & Associates Chartered Accountants',
          registeredAddress: 'Plot 14, Okhla Industrial Area Phase-III, New Delhi - 110020',
        },
        financialTurnover: [
          { financialYear: '2024-25', amount: 5.4, auditedBy: 'M/s K.R. Sharma', udinNumber: '25088194AAAA1294' },
          { financialYear: '2023-24', amount: 4.8, auditedBy: 'M/s K.R. Sharma', udinNumber: '24088194AAAA1102' },
          { financialYear: '2022-23', amount: 3.9, auditedBy: 'M/s K.R. Sharma', udinNumber: '23088194AAAA9941' },
        ],
        submittedDocuments: [
          {
            id: 'DOC-101',
            type: 'GST_CERTIFICATE',
            title: 'GST Certificate (REG-06)',
            documentNumber: '07AAACT4819M1Z8',
            source: 'DIGILOCKER',
            isDigiLockerVerified: true,
            issuer: 'GSTN',
            issuedDate: '2021-03-01',
            checksum: 'a98f12cb894129',
            extractedData: { legalName: 'TechPro SysTech Private Limited', gstin: '07AAACT4819M1Z8' },
          },
          {
            id: 'DOC-102',
            type: 'OEM_AUTHORIZATION',
            title: 'OEM Authorization Letter (Lenovo)',
            documentNumber: 'LEN-MAF-2026-894',
            source: 'DIGILOCKER',
            isDigiLockerVerified: true,
            issuer: 'Lenovo India Pvt Ltd',
            issuedDate: '2026-07-20',
            checksum: 'b81928fa88129',
            extractedData: { oemName: 'Lenovo India', validTender: 'GeM/2026/B/89421' },
          },
        ],
        consentToken: {
          tokenId: 'CST-2026-894-001',
          bidderId: 'BID-001',
          tenderId: 'TND-2026-IT-89421',
          timestamp: '2026-08-15T10:14:20.000Z',
          ipAddress: '103.24.18.91',
          consentedScopes: ['API_SETU', 'DIGILOCKER', 'MCA21', 'CVC_DEBARMENT'],
          signature: 'ECDSA-SHA256-TOKEN-001-OK',
        },
        bidSubmissionDate: '2026-08-15T10:14:20.000Z',
        bidAmount: 47200000,
        makeInIndiaLocalContentPercentage: 62,
        technicalProposalText:
          'TechPro SysTech provides enterprise-grade IT infrastructure deployment with on-site SLA warranty. We maintain local warehousing in Okhla Phase-III and provide certified hardware technicians for immediate 4-hour breakdown resolution across all government directorates.',
      },

      // Bidder 2: NextGen Infotech Pvt Ltd (Collusion Ring Member B - Shares DIN & Address with Bidder 1)
      {
        id: 'BID-002',
        tenderId: 'TND-2026-IT-89421',
        name: 'NextGen Infotech Private Limited',
        tradeName: 'NextGen Systems',
        cin: 'U72200DL2021PTC376890',
        pan: 'AAACN9124L',
        gstin: '07AAACN9124L1ZK',
        udyamNumber: 'UDYAM-DL-08-0019441',
        isMsme: true,
        isStartup: false,
        incorporationDate: '2021-02-22', // 12 days after TechPro!
        registeredAddress: 'Plot 14, Okhla Industrial Area Phase-III, New Delhi - 110020', // Identical Address!
        statutoryAuditor: 'M/s K.R. Sharma & Associates Chartered Accountants', // Identical Auditor!
        directors: [
          {
            din: '08412948', // Identical Director (Sunil Kumar Verma)!
            name: 'Sunil Kumar Verma',
            pan: 'ABIPV8812K',
            appointmentDate: '2021-02-22',
          },
          {
            din: '09124819',
            name: 'Anita Verma',
            pan: 'AAAPV7712M',
            appointmentDate: '2021-02-22',
          },
        ],
        mcaFilings: {
          cin: 'U72200DL2021PTC376890',
          companyName: 'NextGen Infotech Private Limited',
          status: 'ACTIVE',
          rocCode: 'RoC-Delhi',
          registrationNumber: '376890',
          category: 'Company limited by Shares',
          lastAgmDate: '2025-09-28',
          balanceSheetDate: '2025-03-31',
          statutoryAuditor: 'M/s K.R. Sharma & Associates Chartered Accountants',
          registeredAddress: 'Plot 14, Okhla Industrial Area Phase-III, New Delhi - 110020',
        },
        financialTurnover: [
          { financialYear: '2024-25', amount: 4.9, auditedBy: 'M/s K.R. Sharma', udinNumber: '25088194AAAA1440' },
          { financialYear: '2023-24', amount: 4.1, auditedBy: 'M/s K.R. Sharma', udinNumber: '24088194AAAA1198' },
          { financialYear: '2022-23', amount: 3.2, auditedBy: 'M/s K.R. Sharma', udinNumber: '23088194AAAA9120' },
        ],
        submittedDocuments: [
          {
            id: 'DOC-201',
            type: 'GST_CERTIFICATE',
            title: 'GST Certificate (REG-06)',
            documentNumber: '07AAACN9124L1ZK',
            source: 'DIGILOCKER',
            isDigiLockerVerified: true,
            issuer: 'GSTN',
            issuedDate: '2021-03-10',
            checksum: 'b9918239ac98',
            extractedData: { legalName: 'NextGen Infotech Private Limited' },
          },
          {
            id: 'DOC-202',
            type: 'OEM_AUTHORIZATION',
            title: 'OEM Authorization Letter (Lenovo)',
            documentNumber: 'LEN-MAF-2026-895',
            source: 'DIGILOCKER',
            isDigiLockerVerified: true,
            issuer: 'Lenovo India Pvt Ltd',
            issuedDate: '2026-07-20',
            checksum: 'ca9812903841',
            extractedData: { oemName: 'Lenovo India', validTender: 'GeM/2026/B/89421' },
          },
        ],
        consentToken: {
          tokenId: 'CST-2026-894-002',
          bidderId: 'BID-002',
          tenderId: 'TND-2026-IT-89421',
          timestamp: '2026-08-15T11:05:40.000Z',
          ipAddress: '103.24.18.91', // Identical IP Subnet!
          consentedScopes: ['API_SETU', 'DIGILOCKER', 'MCA21', 'CVC_DEBARMENT'],
          signature: 'ECDSA-SHA256-TOKEN-002-OK',
        },
        bidSubmissionDate: '2026-08-15T11:05:40.000Z',
        bidAmount: 47900000,
        makeInIndiaLocalContentPercentage: 62,
        technicalProposalText:
          'NextGen Infotech provides enterprise-grade IT infrastructure deployment with on-site SLA warranty. We maintain local warehousing in Okhla Phase-III and provide certified hardware technicians for immediate 4-hour breakdown resolution across all government directorates.', // Copied proposal!
      },

      // Bidder 3: AeroByte Networks Ltd (Debarred / Blacklisted - Hard Gate Failure)
      {
        id: 'BID-003',
        tenderId: 'TND-2026-IT-89421',
        name: 'AeroByte Networks Limited',
        tradeName: 'AeroByte Tech',
        cin: 'U72200DL2020PTC369999',
        pan: 'AABCE9999K', // Present in Central Debarment DB!
        gstin: '27AABCE9999K1Z5',
        udyamNumber: 'UDYAM-MH-01-0088194',
        isMsme: false,
        isStartup: false,
        incorporationDate: '2020-08-14',
        registeredAddress: 'Level 5, Nariman Point, Mumbai, Maharashtra - 400021',
        statutoryAuditor: 'M/s Batliboi & Mehta LLP',
        directors: [
          {
            din: '06129841',
            name: 'Vikramaditya Singhania',
            pan: 'AAAPS4819Q',
            appointmentDate: '2020-08-14',
          },
        ],
        mcaFilings: {
          cin: 'U72200DL2020PTC369999',
          companyName: 'AeroByte Networks Limited',
          status: 'ACTIVE',
          rocCode: 'RoC-Mumbai',
          registrationNumber: '369999',
          category: 'Company limited by Shares',
          lastAgmDate: '2024-09-30',
          balanceSheetDate: '2024-03-31',
          statutoryAuditor: 'M/s Batliboi & Mehta LLP',
          registeredAddress: 'Level 5, Nariman Point, Mumbai, Maharashtra - 400021',
        },
        financialTurnover: [
          { financialYear: '2024-25', amount: 18.2, auditedBy: 'M/s Batliboi', udinNumber: '25019284AAAA8812' },
        ],
        submittedDocuments: [
          {
            id: 'DOC-301',
            type: 'GST_CERTIFICATE',
            title: 'GST Certificate',
            documentNumber: '27AABCE9999K1Z5',
            source: 'DIGILOCKER',
            isDigiLockerVerified: true,
            issuer: 'GSTN',
            issuedDate: '2020-09-01',
            checksum: 'e9812903841a',
            extractedData: { legalName: 'AeroByte Networks Limited' },
          },
        ],
        consentToken: {
          tokenId: 'CST-2026-894-003',
          bidderId: 'BID-003',
          tenderId: 'TND-2026-IT-89421',
          timestamp: '2026-08-16T14:22:10.000Z',
          ipAddress: '49.207.12.8',
          consentedScopes: ['API_SETU', 'DIGILOCKER', 'MCA21', 'CVC_DEBARMENT'],
          signature: 'ECDSA-SHA256-TOKEN-003-OK',
        },
        bidSubmissionDate: '2026-08-16T14:22:10.000Z',
        bidAmount: 46500000,
        makeInIndiaLocalContentPercentage: 55,
        technicalProposalText:
          'AeroByte Networks delivers complete hardware provisioning with automated imaging and telemetry.',
      },

      // Bidder 4: Apex Digital Solutions LLP (Genuine High-Score MSME)
      {
        id: 'BID-004',
        tenderId: 'TND-2026-IT-89421',
        name: 'Apex Digital Solutions LLP',
        tradeName: 'Apex Digital',
        cin: 'AAB-9841',
        pan: 'AAQFA8129P',
        gstin: '07AAQFA8129P1Z2',
        udyamNumber: 'UDYAM-DL-01-0098412',
        isMsme: true,
        isStartup: true,
        incorporationDate: '2022-04-18',
        registeredAddress: 'Unit 402, Jasola District Centre, New Delhi - 110025',
        statutoryAuditor: 'M/s D.K. Chhajed & Co',
        directors: [
          {
            din: '09812401',
            name: 'Pooja Bhattacharya',
            pan: 'AAAPB4412R',
            appointmentDate: '2022-04-18',
          },
          {
            din: '09812402',
            name: 'Arjun Menon',
            pan: 'AAAPM8819S',
            appointmentDate: '2022-04-18',
          },
        ],
        mcaFilings: {
          cin: 'AAB-9841',
          companyName: 'Apex Digital Solutions LLP',
          status: 'ACTIVE',
          rocCode: 'RoC-Delhi',
          registrationNumber: '9841',
          category: 'Limited Liability Partnership',
          lastAgmDate: '2025-09-15',
          balanceSheetDate: '2025-03-31',
          statutoryAuditor: 'M/s D.K. Chhajed & Co',
          registeredAddress: 'Unit 402, Jasola District Centre, New Delhi - 110025',
        },
        financialTurnover: [
          { financialYear: '2024-25', amount: 6.2, auditedBy: 'M/s D.K. Chhajed', udinNumber: '25091823AAAA7712' },
          { financialYear: '2023-24', amount: 4.5, auditedBy: 'M/s D.K. Chhajed', udinNumber: '24091823AAAA6610' },
        ],
        submittedDocuments: [
          {
            id: 'DOC-401',
            type: 'GST_CERTIFICATE',
            title: 'GST Certificate (REG-06)',
            documentNumber: '07AAQFA8129P1Z2',
            source: 'DIGILOCKER',
            isDigiLockerVerified: true,
            issuer: 'GSTN',
            issuedDate: '2022-05-01',
            checksum: 'fa981239841c',
            extractedData: { legalName: 'Apex Digital Solutions LLP' },
          },
          {
            id: 'DOC-402',
            type: 'OEM_AUTHORIZATION',
            title: 'OEM Authorization (HP Enterprise)',
            documentNumber: 'HPE-MAF-2026-1094',
            source: 'DIGILOCKER',
            isDigiLockerVerified: true,
            issuer: 'Hewlett Packard Enterprise India',
            issuedDate: '2026-07-28',
            checksum: 'da819230948b',
            extractedData: { oemName: 'HPE India', validTender: 'GeM/2026/B/89421' },
          },
        ],
        consentToken: {
          tokenId: 'CST-2026-894-004',
          bidderId: 'BID-004',
          tenderId: 'TND-2026-IT-89421',
          timestamp: '2026-08-17T09:30:15.000Z',
          ipAddress: '115.112.44.18',
          consentedScopes: ['API_SETU', 'DIGILOCKER', 'MCA21', 'CVC_DEBARMENT'],
          signature: 'ECDSA-SHA256-TOKEN-004-OK',
        },
        bidSubmissionDate: '2026-08-17T09:30:15.000Z',
        bidAmount: 46800000,
        makeInIndiaLocalContentPercentage: 74,
        technicalProposalText:
          'Apex Digital Solutions offers end-to-end deployment with HP ProBook enterprise workstations, featuring MIL-STD-810H durability, TPM 2.0 hardware encryption, and 24x7 dedicated tier-1 engineer desk support.',
      },

      // Bidder 5: Vanguard IT Solutions Pvt Ltd (High Risk - Default in GST & Missing OEM Letter)
      {
        id: 'BID-005',
        tenderId: 'TND-2026-IT-89421',
        name: 'Vanguard IT Default Solutions Pvt Ltd',
        tradeName: 'Vanguard Systems',
        cin: 'U72900UP2019PTC118940',
        pan: 'AABCV1940E',
        gstin: '09AABCV1940E1Z7',
        isMsme: false,
        isStartup: false,
        incorporationDate: '2019-06-12',
        registeredAddress: 'B-12, Sector 63, Noida, Uttar Pradesh - 201301',
        statutoryAuditor: 'M/s Verma & Associates',
        directors: [
          {
            din: '05194821',
            name: 'Praveen Yadav',
            pan: 'AAAPY1948N',
            appointmentDate: '2019-06-12',
          },
        ],
        mcaFilings: {
          cin: 'U72900UP2019PTC118940',
          companyName: 'Vanguard IT Default Solutions Pvt Ltd',
          status: 'ACTIVE',
          rocCode: 'RoC-Kanpur',
          registrationNumber: '118940',
          category: 'Company limited by Shares',
          lastAgmDate: '2024-09-30',
          balanceSheetDate: '2024-03-31',
          statutoryAuditor: 'M/s Verma & Associates',
          registeredAddress: 'B-12, Sector 63, Noida, Uttar Pradesh - 201301',
        },
        financialTurnover: [
          { financialYear: '2024-25', amount: 2.1, auditedBy: 'M/s Verma', udinNumber: '25018294AAAA1009' },
        ],
        submittedDocuments: [
          {
            id: 'DOC-501',
            type: 'GST_CERTIFICATE',
            title: 'GST Certificate',
            documentNumber: '09AABCV1940E1Z7',
            source: 'API_SETU',
            isDigiLockerVerified: false,
            issuer: 'GSTN',
            issuedDate: '2019-07-01',
            checksum: 'ea8819234812',
            extractedData: { legalName: 'Vanguard IT Default Solutions Pvt Ltd' },
          },
        ],
        consentToken: {
          tokenId: 'CST-2026-894-005',
          bidderId: 'BID-005',
          tenderId: 'TND-2026-IT-89421',
          timestamp: '2026-08-18T16:40:00.000Z',
          ipAddress: '182.72.10.4',
          consentedScopes: ['API_SETU', 'DIGILOCKER', 'MCA21', 'CVC_DEBARMENT'],
          signature: 'ECDSA-SHA256-TOKEN-005-OK',
        },
        bidSubmissionDate: '2026-08-18T16:40:00.000Z',
        bidAmount: 48500000,
        makeInIndiaLocalContentPercentage: 25,
        technicalProposalText:
          'Vanguard IT proposes standard commercial PCs with third party support and standard distributor fulfillment.',
      },
    ],
  },

  // =========================================================================
  // TENDER 2: Solar Rooftop PV Installation (Make in India Heavy)
  // =========================================================================
  {
    tender: {
      id: 'TND-2026-SOLAR-91034',
      tenderNumber: 'GeM/2026/B/91034',
      title: 'Design, Engineering, Supply and Commissioning of 500kW Grid-Connected Solar Rooftop PV Systems',
      category: 'WORKS',
      estimatedValue: 125000000, // ₹12.50 Cr
      publishedDate: '2026-08-05',
      closingDate: '2026-09-05',
      authority: {
        name: 'Solar Energy Corporation of India (SECI)',
        department: 'Ministry of New and Renewable Energy (MNRE)',
        location: 'NBCC Plaza, Pushp Vihar, New Delhi - 110017',
      },
      description: 'Turnkey execution of 500kWp Solar Rooftop systems on Central Government buildings in Delhi NCR with MNRE ALMM Listed Mono-PERC Modules and 5-Year Comprehensive O&M.',
      requiredDocuments: [
        'GST Registration Certificate',
        'PAN Card',
        'Make in India Class-I Local Content Certificate (≥50%)',
        'MNRE ALMM Enlistment Certificate',
        'Audited Balance Sheets (3 FYs)',
      ],
      clauses: [
        {
          id: 'CLS_SOL_DEBAR',
          clauseNumber: 'Clause 4.1',
          title: 'Debarment Clearance',
          text: 'Clear debarment record required under GFR Rule 151.',
          type: 'HARD_GATE',
          category: 'DEBARMENT',
          defaultWeight: 0,
          isMandatory: true,
          applicableInCategories: ['GOODS', 'SERVICES', 'WORKS'],
        },
        {
          id: 'CLS_SOL_GST',
          clauseNumber: 'Clause 3.1',
          title: 'GST Tax Compliance',
          text: 'Regular GST return filings.',
          type: 'WEIGHTED_CHECK',
          category: 'GST',
          defaultWeight: 20,
          isMandatory: true,
          applicableInCategories: ['GOODS', 'SERVICES', 'WORKS'],
        },
        {
          id: 'CLS_SOL_PAN',
          clauseNumber: 'Clause 3.2',
          title: 'PAN & ITR Compliance',
          text: 'Operative PAN and ITR filings.',
          type: 'WEIGHTED_CHECK',
          category: 'PAN',
          defaultWeight: 15,
          isMandatory: true,
          applicableInCategories: ['GOODS', 'SERVICES', 'WORKS'],
        },
        {
          id: 'CLS_SOL_MII',
          clauseNumber: 'Clause 8.1',
          title: 'Mandatory Class-I Local Supplier (MII)',
          text: 'Minimum 50% domestic value addition using ALMM compliant cells & modules.',
          type: 'WEIGHTED_CHECK',
          category: 'MAKE_IN_INDIA',
          defaultWeight: 25,
          isMandatory: true,
          applicableInCategories: ['WORKS', 'GOODS'],
        },
        {
          id: 'CLS_SOL_FIN',
          clauseNumber: 'Clause 2.4',
          title: 'Turnover & Financial Standing',
          text: 'Minimum annual turnover of ₹5.00 Cr.',
          type: 'WEIGHTED_CHECK',
          category: 'FINANCIAL_TURNOVER',
          defaultWeight: 15,
          isMandatory: true,
          applicableInCategories: ['WORKS'],
        },
      ],
    },
    bidders: [
      {
        id: 'BID-SOL-01',
        tenderId: 'TND-2026-SOLAR-91034',
        name: 'SuryaShakti Solar Energies Limited',
        tradeName: 'SuryaShakti',
        cin: 'U40106DL2018PLC339410',
        pan: 'AAACS8912J',
        gstin: '07AAACS8912J1Z1',
        isMsme: false,
        isStartup: false,
        incorporationDate: '2018-05-20',
        registeredAddress: 'Sector 62, Noida, Gautam Buddha Nagar, UP - 201309',
        statutoryAuditor: 'M/s Singhi & Co Chartered Accountants',
        directors: [
          {
            din: '02819481',
            name: 'Anil Kumar Singhania',
            pan: 'AAAPS1294K',
            appointmentDate: '2018-05-20',
          },
        ],
        mcaFilings: {
          cin: 'U40106DL2018PLC339410',
          companyName: 'SuryaShakti Solar Energies Limited',
          status: 'ACTIVE',
          rocCode: 'RoC-Delhi',
          registrationNumber: '339410',
          category: 'Public Limited Company',
          lastAgmDate: '2025-09-20',
          balanceSheetDate: '2025-03-31',
          statutoryAuditor: 'M/s Singhi & Co',
          registeredAddress: 'Sector 62, Noida, Gautam Buddha Nagar, UP - 201309',
        },
        financialTurnover: [
          { financialYear: '2024-25', amount: 34.5, auditedBy: 'M/s Singhi', udinNumber: '25019284AAAA9921' },
        ],
        submittedDocuments: [],
        consentToken: {
          tokenId: 'CST-SOL-001',
          bidderId: 'BID-SOL-01',
          tenderId: 'TND-2026-SOLAR-91034',
          timestamp: '2026-08-10T11:00:00.000Z',
          ipAddress: '103.11.22.33',
          consentedScopes: ['API_SETU', 'DIGILOCKER', 'MCA21', 'CVC_DEBARMENT'],
          signature: 'ECDSA-SHA256-SOL-001-OK',
        },
        bidSubmissionDate: '2026-08-10T11:00:00.000Z',
        bidAmount: 119000000,
        makeInIndiaLocalContentPercentage: 78, // Class-I Local Supplier
        technicalProposalText: 'SuryaShakti proposes 540Wp Tier-1 MNRE ALMM Approved DCR Mono-PERC modules with string inverters.',
      },
      {
        id: 'BID-SOL-02',
        tenderId: 'TND-2026-SOLAR-91034',
        name: 'IndoSun Imported PV Systems Pvt Ltd',
        tradeName: 'IndoSun Power',
        cin: 'U40300MH2020PTC348120',
        pan: 'AAACI7712M',
        gstin: '27AAACI7712M1Z9',
        isMsme: false,
        isStartup: false,
        incorporationDate: '2020-03-15',
        registeredAddress: 'Andheri East, Mumbai - 400069',
        statutoryAuditor: 'M/s Parekh & Shah',
        directors: [
          {
            din: '08192301',
            name: 'Rohan Deshmukh',
            pan: 'AAAPD9912L',
            appointmentDate: '2020-03-15',
          },
        ],
        mcaFilings: {
          cin: 'U40300MH2020PTC348120',
          companyName: 'IndoSun Imported PV Systems Pvt Ltd',
          status: 'ACTIVE',
          rocCode: 'RoC-Mumbai',
          registrationNumber: '348120',
          category: 'Private Limited Company',
          lastAgmDate: '2025-09-18',
          balanceSheetDate: '2025-03-31',
          statutoryAuditor: 'M/s Parekh & Shah',
          registeredAddress: 'Andheri East, Mumbai - 400069',
        },
        financialTurnover: [
          { financialYear: '2024-25', amount: 8.2, auditedBy: 'M/s Parekh', udinNumber: '25019284AAAA3312' },
        ],
        submittedDocuments: [],
        consentToken: {
          tokenId: 'CST-SOL-002',
          bidderId: 'BID-SOL-02',
          tenderId: 'TND-2026-SOLAR-91034',
          timestamp: '2026-08-11T15:30:00.000Z',
          ipAddress: '115.118.99.12',
          consentedScopes: ['API_SETU', 'DIGILOCKER', 'MCA21', 'CVC_DEBARMENT'],
          signature: 'ECDSA-SHA256-SOL-002-OK',
        },
        bidSubmissionDate: '2026-08-11T15:30:00.000Z',
        bidAmount: 114000000,
        makeInIndiaLocalContentPercentage: 14, // Non-local supplier (<20%) -> Fails threshold!
        technicalProposalText: 'IndoSun proposes imported solar PV modules assembled with non-DCR silicon cells.',
      },
    ],
  },

  // =========================================================================
  // TENDER 3: Facility Management Services (Demonstrates Dynamic Weight Redistribution)
  // =========================================================================
  {
    tender: {
      id: 'TND-2026-FM-77120',
      tenderNumber: 'GeM/2026/B/77120',
      title: 'Integrated Facility Management, Housekeeping and Sanitization Services',
      category: 'SERVICES',
      estimatedValue: 21000000, // ₹2.10 Cr
      publishedDate: '2026-08-08',
      closingDate: '2026-09-08',
      authority: {
        name: 'All India Institute of Medical Sciences (AIIMS)',
        department: 'Estate & Hospital Administration',
        location: 'Ansari Nagar, New Delhi - 110029',
      },
      description: 'Round-the-clock integrated housekeeping, waste management, and disinfection services for hospital wards with 120 deployed trained personnel.',
      requiredDocuments: [
        'GST Registration Certificate',
        'PAN Card',
        'EPFO Registration and Latest ECR Receipt',
        'ESIC Registration Certificate',
        'Labor License under Contract Labor Act 1970',
      ],
      clauses: [
        {
          id: 'CLS_FM_DEBAR',
          clauseNumber: 'Clause 4.1',
          title: 'Debarment Clearance',
          text: 'Clear debarment record required under GFR Rule 151.',
          type: 'HARD_GATE',
          category: 'DEBARMENT',
          defaultWeight: 0,
          isMandatory: true,
          applicableInCategories: ['GOODS', 'SERVICES', 'WORKS'],
        },
        {
          id: 'CLS_FM_GST',
          clauseNumber: 'Clause 3.1',
          title: 'GST Compliance',
          text: 'Regular GST return filings.',
          type: 'WEIGHTED_CHECK',
          category: 'GST',
          defaultWeight: 20,
          isMandatory: true,
          applicableInCategories: ['SERVICES'],
        },
        {
          id: 'CLS_FM_PAN',
          clauseNumber: 'Clause 3.2',
          title: 'PAN & Income Tax',
          text: 'Operative PAN and ITR filings.',
          type: 'WEIGHTED_CHECK',
          category: 'PAN',
          defaultWeight: 15,
          isMandatory: true,
          applicableInCategories: ['SERVICES'],
        },
        {
          id: 'CLS_FM_EPFO',
          clauseNumber: 'Clause 7.3',
          title: 'Mandatory EPFO / ESIC Manpower Social Security',
          text: 'Active EPFO establishment with proof of monthly ECR challan remittances for >100 workers.',
          type: 'WEIGHTED_CHECK',
          category: 'EPFO_ESIC',
          defaultWeight: 25,
          isMandatory: true,
          applicableInCategories: ['SERVICES'],
        },
        {
          id: 'CLS_FM_UDYAM',
          clauseNumber: 'Clause 5.1',
          title: 'Udyam Registration',
          text: 'MSME registration status and benefits.',
          type: 'WEIGHTED_CHECK',
          category: 'UDYAM',
          defaultWeight: 15,
          isMandatory: false,
          applicableInCategories: ['SERVICES'],
          exemptionForMSME: true,
        },
        {
          id: 'CLS_FM_FIN',
          clauseNumber: 'Clause 2.4',
          title: 'Financial Standing & Reconciliation',
          text: 'Annual turnover of minimum ₹1.5 Cr.',
          type: 'WEIGHTED_CHECK',
          category: 'FINANCIAL_TURNOVER',
          defaultWeight: 10,
          isMandatory: true,
          applicableInCategories: ['SERVICES'],
        },
      ],
    },
    bidders: [
      {
        id: 'BID-FM-01',
        tenderId: 'TND-2026-FM-77120',
        name: 'CleanForce Facility Care Solutions Pvt Ltd',
        tradeName: 'CleanForce Care',
        cin: 'U74999DL2017PTC318920',
        pan: 'AAACC8912P',
        gstin: '07AAACC8912P1Z4',
        udyamNumber: 'UDYAM-DL-01-0018942',
        epfoNumber: 'DL/CPM/0048192/000',
        esicNumber: '11000984120001001',
        isMsme: true,
        isStartup: false,
        incorporationDate: '2017-09-12',
        registeredAddress: 'South Extension Part-II, New Delhi - 110049',
        statutoryAuditor: 'M/s Gupta & Sehgal LLP',
        directors: [
          {
            din: '07819201',
            name: 'Deepak Mehrotra',
            pan: 'AAAPM1948R',
            appointmentDate: '2017-09-12',
          },
        ],
        mcaFilings: {
          cin: 'U74999DL2017PTC318920',
          companyName: 'CleanForce Facility Care Solutions Pvt Ltd',
          status: 'ACTIVE',
          rocCode: 'RoC-Delhi',
          registrationNumber: '318920',
          category: 'Private Limited Company',
          lastAgmDate: '2025-09-22',
          balanceSheetDate: '2025-03-31',
          statutoryAuditor: 'M/s Gupta & Sehgal LLP',
          registeredAddress: 'South Extension Part-II, New Delhi - 110049',
        },
        financialTurnover: [
          { financialYear: '2024-25', amount: 8.9, auditedBy: 'M/s Gupta & Sehgal', udinNumber: '25019284AAAA5512' },
        ],
        submittedDocuments: [],
        consentToken: {
          tokenId: 'CST-FM-001',
          bidderId: 'BID-FM-01',
          tenderId: 'TND-2026-FM-77120',
          timestamp: '2026-08-12T10:00:00.000Z',
          ipAddress: '103.45.19.82',
          consentedScopes: ['API_SETU', 'DIGILOCKER', 'MCA21', 'CVC_DEBARMENT'],
          signature: 'ECDSA-SHA256-FM-001-OK',
        },
        bidSubmissionDate: '2026-08-12T10:00:00.000Z',
        bidAmount: 20400000,
        technicalProposalText: 'CleanForce deploys certified sanitization teams with mechanised floor scrubbers, bio-medical waste compliance, and real-time biometric staff attendance.',
      },
      {
        id: 'BID-FM-02',
        tenderId: 'TND-2026-FM-77120',
        name: 'Apex Care Unregistered Services',
        tradeName: 'Apex Care',
        cin: 'U74900DL2022PTC394120',
        pan: 'AAACA9912K',
        gstin: '07AAACA9912K1Z8',
        // Missing EPFO number!
        isMsme: true,
        isStartup: false,
        incorporationDate: '2022-08-10',
        registeredAddress: 'Pitampura, New Delhi - 110034',
        statutoryAuditor: 'M/s R.K. Jain & Co',
        directors: [
          {
            din: '09129481',
            name: 'Sunita Jain',
            pan: 'AAAPJ9124K',
            appointmentDate: '2022-08-10',
          },
        ],
        mcaFilings: {
          cin: 'U74900DL2022PTC394120',
          companyName: 'Apex Care Unregistered Services',
          status: 'ACTIVE',
          rocCode: 'RoC-Delhi',
          registrationNumber: '394120',
          category: 'Private Limited Company',
          lastAgmDate: '2025-09-12',
          balanceSheetDate: '2025-03-31',
          statutoryAuditor: 'M/s R.K. Jain & Co',
          registeredAddress: 'Pitampura, New Delhi - 110034',
        },
        financialTurnover: [
          { financialYear: '2024-25', amount: 1.8, auditedBy: 'M/s R.K. Jain', udinNumber: '25019284AAAA1129' },
        ],
        submittedDocuments: [],
        consentToken: {
          tokenId: 'CST-FM-002',
          bidderId: 'BID-FM-02',
          tenderId: 'TND-2026-FM-77120',
          timestamp: '2026-08-14T12:15:00.000Z',
          ipAddress: '115.112.9.20',
          consentedScopes: ['API_SETU', 'DIGILOCKER', 'MCA21', 'CVC_DEBARMENT'],
          signature: 'ECDSA-SHA256-FM-002-OK',
        },
        bidSubmissionDate: '2026-08-14T12:15:00.000Z',
        bidAmount: 19800000,
        technicalProposalText: 'Apex Care provides basic housekeeping and cleaning services on a contract basis.',
      },
    ],
  },
];
